Fix Zulip integration secrets in vulnerability scan workflow
Signed-off-by: Matheus Pimenta <matheuscscp@gmail.com>

diff --git a/.github/workflows/scan-controllers.yaml b/.github/workflows/scan-controllers.yaml
--- a/.github/workflows/scan-controllers.yaml
+++ b/.github/workflows/scan-controllers.yaml
@@ -17,10 +17,27 @@ on:
         required: false
         type: boolean
         default: true
+      caller-job:
+        description: 'job that called this workflow'
+        required: false
+        type: string
+      variant:
+        description: 'controller variant'
+        type: string
+        required: false
     secrets:
       pull-token:
         description: 'GitHub Container Registry read-only token'
         required: true
+      zulip-email:
+        description: 'Zulip email'
+        required: false
+      zulip-api-key:
+        description: 'Zulip API key'
+        required: false
+      zulip-organization-url:
+        description: 'Zulip organization URL'
+        required: false
 
 jobs:
   trivy:
@@ -152,32 +169,30 @@ jobs:
           echo "image-automation-controller: ${{ steps.iac.outcome }}"
           echo "image: ${{ steps.images.outputs.iac }}"
       - name: Get Job URL
-        if: steps.sc.outcome == 'failure' || steps.kc.outcome == 'failure' || steps.hc.outcome == 'failure' || steps.nc.outcome == 'failure' || steps.irc.outcome == 'failure' || steps.iac.outcome == 'failure'
+        if: inputs.check-scan-error && (steps.sc.outcome == 'failure' || steps.kc.outcome == 'failure' || steps.hc.outcome == 'failure' || steps.nc.outcome == 'failure' || steps.irc.outcome == 'failure' || steps.iac.outcome == 'failure')
         id: job-url
         run: |
           url=$(gh run view ${GITHUB_RUN_ID} --repo ${GITHUB_REPO} --json jobs --jq ".jobs[] | select(.name == \"${GITHUB_JOB}\") | .url")
           echo "url: $url"
           echo url=$url >> $GITHUB_OUTPUT
         env:
-          GITHUB_JOB: ${{ github.job }}
+          GITHUB_JOB: ${{ inputs.caller-job }} / ${{ github.job }}
           GITHUB_RUN_ID: ${{ github.run_id }}
           GITHUB_REPO: ${{ github.repository }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
-        if: steps.sc.outcome == 'failure' || steps.kc.outcome == 'failure' || steps.hc.outcome == 'failure' || steps.nc.outcome == 'failure' || steps.irc.outcome == 'failure' || steps.iac.outcome == 'failure'
+        if: inputs.check-scan-error && (steps.sc.outcome == 'failure' || steps.kc.outcome == 'failure' || steps.hc.outcome == 'failure' || steps.nc.outcome == 'failure' || steps.irc.outcome == 'failure' || steps.iac.outcome == 'failure')
         with:
-          email: ${{ secrets.ZULIP_EMAIL }}
-          api-key: ${{ secrets.ZULIP_API_KEY }}
-          organization-url: ${{ secrets.ZULIP_ORGANIZATION_URL }}
+          email: ${{ secrets.zulip-email }}
+          api-key: ${{ secrets.zulip-api-key }}
+          organization-url: ${{ secrets.zulip-organization-url }}
           type: stream
           to: team-flux
           topic: cve-alerts
-          content: 'Flux Enterprise ${{ github.job }} CVE alert: ${{ steps.job-url.outputs.url }}'
+          content: 'Flux Enterprise ${{ inputs.variant }} CVE alert: ${{ steps.job-url.outputs.url }}'
       - name: Check result
         shell: bash
-        if: steps.sc.outcome == 'failure' || steps.kc.outcome == 'failure' || steps.hc.outcome == 'failure' || steps.nc.outcome == 'failure' || steps.irc.outcome == 'failure' || steps.iac.outcome == 'failure'
+        if: inputs.check-scan-error && (steps.sc.outcome == 'failure' || steps.kc.outcome == 'failure' || steps.hc.outcome == 'failure' || steps.nc.outcome == 'failure' || steps.irc.outcome == 'failure' || steps.iac.outcome == 'failure')
         run: |
           echo "One or more controllers have vulnerabilities"
-          if [ "${{ inputs.check-scan-error }}" = "true" ]; then
-            exit 1
-          fi
+          exit 1
